#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#define MAX 20
#define WORDS 550

void wordlist(char *a)
{
	char b[][MAX] = {"help", "safe", "nothing", "brilliant", "gem",
		 "car", "break", "peel", "fast", "beacon", "rendition",
		  "heavy" , "press", "riddle" ,"skate", "throne","inquisitive",
		  "brass","plain", "uptight","bed","disagreeable","friendly",
		  "phone", "wilderness", "bawdy", "grate", "carpenter","angle",
		  "neighborly","railway","plantation","garrulous","support",
		  "fireman","adventurous","crib","nice","cooing","flower",
		  "earthquake","lonely","moan","symptomatic","blushing","funny",
		  "troubled","beautiful","argue","breath","shoes","dress",
		  "request","soup","open","towering","lively","race",
		  "combative","abundant","furniture","trade","friction","arch",
		  "basketball","selection","unwieldy","jeans","part","bump",
		  "chickens","pest","hop","fuel","synonymous","late","bizarre",
		  "lively","scent","wise","branch","judge","first","level",
		  "torpid","list","decision","flow","actor","slip","challenge",
		  "bulb","coil","lamentable","pipe","clumsy","lush", "wakeful",
		  "delay","female","hollow","quartz","badge","chase","prose",
		  "vast","stiff","famous","real","remove","evasive","puffy",
		  "various","note","pig","soda","sin","toothsome","attraction",
		  "cool","murky","teeny","sincere","full","transport","reason",
		  "waiting","uneven","witty","animal","truculent","field",
		  "pass","premium","sassy","believe","half","boorish","happen",
		  "overt","sordid","general","weigh","chess","exotic","horn",
		  "board","jewel","bitter","rule","harmony","greasy","dream",
		  "cultured","wait","dance","free","insect","living","snow",
		  "spill","undesirable","metal","reflective","inconclusive",
		  "oranges","zoo","cherry","calm","detailed","extra-large",
		  "stop","kind","bleach","knowing","unit","flag","abrasive",
		  "receive","tie","paltry","defective","poke","cap","brick",
		  "table","distribution","office","taste","bird","scientific",
		  "ruthless","gold","quill","road","envious","fold","jolly",
		  "stick","hushed","cut","flight","tired","fair","ants",
		  "intelligent","shake","discreet","produce","dirty","tawdry",
		  "mend","work","humdrum","theory","egg","plot","historical",
		  "gaudy","rainstorm","complex","orange","form","tour","cure",
		  "grip","overflow","tested","adhesive","earth","pinch",
		  "wanting","sick","abounding","kill","stingy","refuse",
		  "memory","oven","moor","internal","lazy","beef","terrible",
		  "base","stretch","impulse","demonic","scarf","savory","shame",
		  "thin","sheet","fantastic","grape","nerve","glib","bath",
		  "birthday","present","bat","kick","question","soft","macho",
		  "righteous","arithmetic","seat","somber","boiling","needle",
		  "straight","bewildered","ragged","snatch","zip","outstanding",
		  "dramatic","secretary","describe","peep","jobless","guttural",
		  "second","umbrella","cats","pull","territory","degree",
		  "lettuce","hole","fade","tame","cows","acoustics","point",
		  "income","name","direful","detect","squeamish","quilt",
		  "obscene","luxuriant","fact","typical","chief","end",
		  "well-off","sleepy","button","circle","spiders","zesty",
		  "dolls","system","equal","excuse","ghost","history","jagged",
		  "root","connection","corn","hang","introduce","church",
		  "dinosaurs","childlike","bee","uttermost","awesome","hall",
		  "love","concern","glorious","nappy","legs","glamorous","miss",
		  "calculate","paddle","damaged","unite","hook","locket",
		  "white","extend","debonair","productive","tumble","precede",
		  "ubiquitous","rejoice","educated","fire","adjustment",
		  "volatile","aloof","modern","increase","slow","flagrant",
		  "merciful","unhealthy","scare","fang","alive","butter","fold",
		  "magic","discovery","selfish","trashy","rebel","smooth",
		  "fail","bathe","representative","crowded","label","gigantic",
		  "interest","glow","honorable","unruly","maniacal","endurable",
		  "mark","curvy","gabby","drawer","fit","foolish","nest",
		  "toothpaste","permissible","frequent","rings","weary","lean",
		  "cherries","cup","war","enchanted","materialistic","replace",
		  "gusty","pointless","warlike","flaky","title","pump",
		  "sidewalk","box","special","smoke","realise","stranger",
		  "round","vegetable","numerous","incandescent","pets",
		  "hapless","encourage","wall","act","lame","silky","godly",
		  "forgetful","tasteful","joyous","apparatus","puzzling",
		  "delirious","vigorous","honey","man","damp","skillful",
		  "greet","tough","notebook","machine","wind","dashing",
		  "untidy","nonstop","rule","amused","defeated","valuable",
		  "sink","volleyball","wire","perfect","yoke","mess","up",
		  "spurious","watch","caring","familiar","annoying","aware",
		  "erect","penitent","beginner","snail","gratis","graceful",
		  "spark","selective","gleaming","push","alarm","number","line",
		  "tan","fetch","jelly","creepy","brake","talented","snails",
		  "parsimonious","jittery","efficient","guess","dead","coach",
		  "ducks","windy","racial","development","acidic","dry","blot",
		  "knotty","expect","zealous","staking","bang","window",
		  "partner","lamp","neat","new","obsequious","apparel"};
	srand(time(NULL));
	int n = rand() % 512;
	strcpy(a, b[n]);
}

